"""Thin Python SDK for the local AgentGit authority daemon."""

from .client import AuthorityClient
from .constants import API_VERSION
from .demo import main as demo_main
from .errors import (
    AuthorityClientTransportError,
    AuthorityClientTransportErrorCode,
    AuthorityDaemonResponseError,
)
from .helper import (
    COMPARE_STEPS,
    EXPLAIN_POLICY_DECISION,
    EXTERNAL_SIDE_EFFECTS,
    HELPER_QUESTION_TYPES,
    IDENTIFY_EXTERNAL_EFFECTS,
    LIKELY_CAUSE,
    LIST_ACTIONS_TOUCHING_SCOPE,
    PREVIEW_REVERT_LOSS,
    REVERSIBLE_STEPS,
    REVERT_IMPACT,
    RUN_SUMMARY,
    SUGGEST_LIKELY_CAUSE,
    STEP_DETAILS,
    SUMMARIZE_AFTER_BOUNDARY,
    WHAT_CHANGED_AFTER_STEP,
    WHAT_HAPPENED,
    WHAT_WOULD_I_LOSE_IF_I_REVERT_HERE,
    WHY_BLOCKED,
)
from .session import build_register_run_payload
from .tools import (
    build_action_attempt,
    build_draft_add_label_attempt,
    build_draft_archive_attempt,
    build_draft_create_attempt,
    build_draft_delete_attempt,
    build_draft_remove_label_attempt,
    build_draft_restore_attempt,
    build_draft_unarchive_attempt,
    build_draft_update_attempt,
    build_note_archive_attempt,
    build_note_create_attempt,
    build_note_delete_attempt,
    build_note_restore_attempt,
    build_note_unarchive_attempt,
    build_note_update_attempt,
    build_ticket_add_label_attempt,
    build_ticket_assign_user_attempt,
    build_ticket_close_attempt,
    build_ticket_create_attempt,
    build_ticket_delete_attempt,
    build_ticket_remove_label_attempt,
    build_ticket_reopen_attempt,
    build_ticket_restore_attempt,
    build_ticket_unassign_user_attempt,
    build_ticket_update_attempt,
    build_filesystem_delete_attempt,
    build_filesystem_write_attempt,
    build_shell_attempt,
)

__all__ = [
    "API_VERSION",
    "AuthorityClient",
    "AuthorityClientTransportError",
    "AuthorityClientTransportErrorCode",
    "AuthorityDaemonResponseError",
    "COMPARE_STEPS",
    "EXPLAIN_POLICY_DECISION",
    "EXTERNAL_SIDE_EFFECTS",
    "HELPER_QUESTION_TYPES",
    "IDENTIFY_EXTERNAL_EFFECTS",
    "LIKELY_CAUSE",
    "LIST_ACTIONS_TOUCHING_SCOPE",
    "PREVIEW_REVERT_LOSS",
    "REVERSIBLE_STEPS",
    "REVERT_IMPACT",
    "RUN_SUMMARY",
    "SUGGEST_LIKELY_CAUSE",
    "STEP_DETAILS",
    "SUMMARIZE_AFTER_BOUNDARY",
    "WHAT_CHANGED_AFTER_STEP",
    "WHAT_HAPPENED",
    "WHAT_WOULD_I_LOSE_IF_I_REVERT_HERE",
    "WHY_BLOCKED",
    "build_action_attempt",
    "build_draft_add_label_attempt",
    "build_draft_archive_attempt",
    "build_draft_create_attempt",
    "build_draft_delete_attempt",
    "build_draft_remove_label_attempt",
    "build_draft_restore_attempt",
    "build_draft_unarchive_attempt",
    "build_draft_update_attempt",
    "build_note_archive_attempt",
    "build_note_create_attempt",
    "build_note_delete_attempt",
    "build_note_restore_attempt",
    "build_note_unarchive_attempt",
    "build_note_update_attempt",
    "build_ticket_add_label_attempt",
    "build_ticket_assign_user_attempt",
    "build_ticket_close_attempt",
    "build_ticket_create_attempt",
    "build_ticket_delete_attempt",
    "build_ticket_remove_label_attempt",
    "build_ticket_reopen_attempt",
    "build_ticket_restore_attempt",
    "build_ticket_unassign_user_attempt",
    "build_ticket_update_attempt",
    "build_filesystem_delete_attempt",
    "build_filesystem_write_attempt",
    "build_register_run_payload",
    "build_shell_attempt",
    "demo_main",
]
